version: '3'
services:
    collector:
        build: collector
        networks:
            - appnet
        environment:
            VIEWER_ADDR: "http://viewer:3000/collect"
        volumes:
            - ./collector:/go/src/github.com/dak0rn/docker-swarm-example/collector
            - /var/run/docker.sock:/var/run/docker.sock

    redis:
        image: redis
        networks:
            - appnet

    viewer:
        build: viewer
        ports:
            - 4000:3000
        networks:
            - appnet
        environment:
            REDIS_ADDR: "redis:6379"
        volumes:
            - ./viewer:/go/src/github.com/dak0rn/docker-swarm-example/viewer

networks:
    appnet:

# vim: et:sw=4:tw=4
